project:
  type: website
  output-dir: docs
  
website:
  title: "Multiomics analysis of Menstrual Effluent"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - libs.qmd
      - NMRanalytics.qmd
      - composition.qmd
      - demographics.qmd
      - stability.qmd
      - prediction.qmd
    tools:
      - icon: envelope
        icon_pack: fas
        link: "mailto:mortenr@food.ku.dk"
      - icon: github
        href: https://github.com/mortenarendt/multiomics_menstrual_effluent
    pinned: true
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2026, Morten Arendt Rasmussen"

format:
  html:
    theme: theme.scss #pulse (purple)
    toc: true
    code-fold: true
    code-summary: "Show code"

editor: source

