---
title: "Longitudinal multi-omics profiling of menstrual effluent reveals personalized metabolic and microbial signatures"
---

## Abstract 
Women’s diseases are highly prevalent and impose substantial individual and societal burdens, yet research in women’s health remains comparatively underprioritized, resulting in slow progress and persistent diagnostic challenges. Menstrual effluent (ME) originates directly from the uterine environment where many gynecological conditions arise, and therefore represents an easily accessible, non-invasive biospecimen with considerable diagnostic potential. However, its chemical and microbial composition has not been comprehensively characterized, limiting translational progress.
In this study, we performed 1H NMR–based metabolomics, 16S rRNA sequencing, and ITS-fungal profiling on longitudinal ME samples collected from 19 healthy women over three consecutive menstrual cycles, alongside matched plasma metabolomics acquired on cycle day 3. We found that the metabolite profile of ME was surprisingly different from peripheral blood (PB) samples. Further, ME samples exhibited pronounced intra-individual stability, with consistent metabolic and microbial signatures across cycles. The cycle day variation was primarily cycle day 1 distinguishing from cycle day 2 and cycle day 3. Analysis of the meta-data showed that nicotine usage and dietary habits had significant influence on both ME metabolome and bacteria but did not significantly influence PB. Machine learning models based on microbial data could predict the concentration of few metabolites, primarily organic acids, indicating that both the microbiomes and the host processes are projected in the ME composition. Our findings demonstrate that ME is a chemically and microbially stable biospecimen within individual, which supports the feasibility of ME as a reliable and biologically informative specimen for much needed diagnostic and prognostic applications in multiple women’s diseases.


Isabella France Jarsmer(1,2), Iva Sunic(3), Yongxin Ye(2), Nilo Vahman(4), Kenneth Klingenberg Barfod(2), Ole Mogensen(5), Bekzod Khakimov(2), Morten Arendt Rasmussen(2,5)

1) Department of Biomedicine, Aarhus University, Aarhus, Denmark 
2) Department of Food Science, University of Copenhagen, Frederiksberg, Denmark 
3) Centre for Applied Bioanthropology, Institute for Anthropological Research, 10000 Zagreb, Croatia
4) Copenhagen Studies on Asthma in Childhood (COPSAC), Herlev- Gentofte Hospitals, University of Copenhagen, Gentofte, Denmark
5) Department of Gynecology and Obstetrics, Aarhus University Hospital, Aarhus, Denmark 


